on:
  push:
    branches:
      - 'main'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - id: build-publish
        uses: bitovi/github-actions-react-to-ghp@v1.1.1
          path: dist